jobs:
  include:
    - stage: coverage_tests
      language: node_js
      node_js:
        - '6.14'
    -  # stage name not required, will continue to use `test`
      language: node_js
      node_js:
        - '8'
    - # stage name not required, will continue to use `test`
      language: node_js
      node_js:
        - '10'
    - # stage name not required, will continue to use `test`
      language: node_js
      node_js:
        - '12'
    - stage: e2e-v8  # these can be made parallel by using different accounts or names
      language: node_js
      node_js:
        - '8'
      script:
        - npm install -g js-yaml
        - bash ./test-functional/e2evars.sh
    - stage: e2e-v10
      language: node_js
      node_js:
        - '10'
      script:
        - npm install -g js-yaml
        - bash ./test-functional/e2evars.sh
    - stage: e2e-v12
      language: node_js
      node_js:
        - '12'
      script:
        - npm install -g js-yaml
        - bash ./test-functional/e2evars.sh
notifications:
  slack:
    secure: RK3HxQ0I107uWCqq+yhfLwiJMBFqnkXq0fyZGbX3TuhIeVXG3huyuwzSVt3NHVX1KJiWbKuFnJOKFfIRPlZEVxrlqOHEoqUhwjC4Zt35QGBrSZQJF6aSKsL2qe8U042zcClrKDvZ4Ool34XAU255LKgeIJVkOmn8gYe/LIfUETGrbWxM1sm03cUpdXwy9ggDVLKifE8SJ/ZDXmzwCx9M/t/1BTX90u6OUsQHJbpkEkbAD8U3vCM49tdmnpV0lh0JZoQwf74+O5c1zE3yj0uDfGz9HAXUJ84Fcr8OAwBFlooUCKLbmWOi4aETzU/byzI6H//d1gGAydHrqnbb+esRr4UD7NvWQQP77ZcAOLeII3rDepzkCJ8ozi5ht246gIwimO2SbJ378tu9sfEaZo6bVXqg8FkNq/G1Swu/5gp9xp5r02lMRkQpIovXMe3o2emYjRF/zHJAKye9ISAHP0yXrqYUZDwn/Ll2OtgSYXg5/hP0R5CGWX8yr6ahOVGHJiF1ndQMnyUrLMAT4WPrd/joFWCmJsd/p8jncqaZYrjVb+FhuMfjUatmXSYY6cVV3aV+kgZyHuLTKQNa7Hp40I836lUAu+qOEZ8jwIKYWS5N8ge0IN2XVpE4JMfG/7UW1r9N7MY24pvNQww0NDPi5Zd1bQPurWwjnBV5YGHc5XGe2/8=
    on_success: never
    on_failure: always
    on_start: never
